# Generated by Django 4.2.5 on 2023-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('time_unblock', models.DateTimeField(blank=True, verbose_name='Время разблокировки')),
                ('status', models.BooleanField(default=True, verbose_name='Статус блокировки')),
            ],
            options={
                'db_table': 'BanIp',
            },
        ),
        migrations.DeleteModel(
            name='TemporaryBanIp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
