# Generated by Django 4.2.5 on 2023-09-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_banip_delete_temporarybanip_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banip',
            table='ban_ip',
        ),
    ]
