# Generated by Django 4.2.5 on 2023-09-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_banip_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
