# Generated by Django 4.2.5 on 2023-09-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_date_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
