# Generated by Django 4.2.5 on 2023-11-27 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(default='Нет описания', max_length=200, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ComplaintArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_complaint', models.SmallIntegerField(choices=[('1', 'Спам'), ('2', 'Запрещенный контент'), ('3', 'Обман'), ('4', 'Насилие и вражда')], verbose_name='Тип жалобы')),
                ('status', models.CharField(choices=[('pending', 'В рассмотрении'), ('satisfied', 'Удовлетворена'), ('rejected', 'Отклонена')], default='pending', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
